# Generated by Django 4.2.7 on 2024-01-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_question_quiz_alter_question_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quizMark',
            field=models.IntegerField(default=1),
        ),
    ]
