# Generated by Django 4.2.7 on 2024-01-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_alter_quizrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizhistory',
            name='totalMarks',
            field=models.IntegerField(default=0),
        ),
    ]
