# Generated by Django 4.2.7 on 2024-01-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_userquizhistory_totalmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizhistory',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, related_name='selected_choices', to='quizzes.choice'),
        ),
    ]
