# Generated by Django 5.0.1 on 2024-01-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_userquizhistory_selected_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-23 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the quiz', null=True, upload_to='quizzes/media/uploads'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
