# Generated by Django 5.0.1 on 2024-01-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_quiz_created_at_quiz_image_quiz_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='quizzes/media/uploads'),
        ),
    ]
